### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by auxfuse** [auxfuse/Dec_Hackathon_22#2]
- single page (index.html)
- 3 sections (landing / about product / examples of product) on page
- navbar
- footer

Consider creation of additional wireframes for supplementary pages ( our team page for example... )

**Comment by auxfuse** [comment]
- single page
- 3 sections (landing / about product / examples of product) on page
- navbar
- footer

**Comment by tanisecarvalho** [comment]
Version 1 of wireframes.

Web:



![Image](https://user-images.githubusercontent.com/15631445/208245239-6194f67d-b634-4d4f-b586-2720a9fd983b.png)


Mobile:



![Image](https://user-images.githubusercontent.com/15631445/208245246-fb7e9533-1d84-4802-aceb-8dbb6986abae.png)
